version: "3"
services:
  api: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/bikeapp?pgbouncer=true&pool_timeout=0
      GOOGLE_MAPS_KEY: AIzaSyBaflWt6miKwVvW8O6yHYVSEUrtVeHsYsk
    depends_on: 
     - db
  db:
      image: postgres
      restart: always
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: "bikeapp"